=== sighttviewliu/xdIm/xdIm_WxPython/control/xml/userSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/userSchema" xmlns:tns="http://www.example.org/userSchema" elementFormDefault="qualified">


    <complexType name="friendlist">
    	<sequence>
    		<element name="name" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="user">
    	<sequence>
    		<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="password" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="friends" type="tns:friendlist" minOccurs="0" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    

    <complexType name="userlist">
    	<sequence>
    		<element name="user" type="tns:user" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <element name="userlist" type="tns:userlist"></element>
</schema>

=== sighttviewliu/xdIm/xdIm_WxPython/control/xml/test.xml
<?xml version="1.0" ?><tns:userlist xmlns:tns="http://www.example.org/userSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/userSchema userSchema.xsd ">
  <tns:user>
  	<tns:name>admin</tns:name>
  	<tns:password>admin</tns:password>
  	<tns:friends>
  		<tns:name>admin</tns:name>
  		<tns:name>xd</tns:name>
  	<tns:name>moon</tns:name></tns:friends>
  </tns:user>
  <tns:user>
  	<tns:name>xd</tns:name>
  	<tns:password>apples9</tns:password>
  	<tns:friends>
  		<tns:name>admin</tns:name>
  		<tns:name>moon</tns:name>
  	</tns:friends>
  </tns:user>
  <tns:user>
    <tns:name>cvs</tns:name>
    <tns:password>apples</tns:password>
    <tns:friends>
      <tns:name>admin</tns:name>
      <tns:name>moon</tns:name>
    </tns:friends>
  </tns:user>
  <tns:user>
  	<tns:name>moon</tns:name>
  	<tns:password>password</tns:password>
  	<tns:friends>
  		<tns:name>admin</tns:name>
  	</tns:friends>
  </tns:user>
  <tns:user>
  	<tns:name>tns:name</tns:name>
  	<tns:password>zz</tns:password>
  	<tns:friends>
  		<tns:name>xd</tns:name></tns:friends>
  </tns:user>
<tns:user><tns:name>cc</tns:name><tns:password>apples</tns:password><tns:friends><tns:name>admin</tns:name><tns:name>mm</tns:name></tns:friends></tns:user><tns:user><tns:name>mm</tns:name><tns:password>apples</tns:password><tns:friends><tns:name>admin</tns:name></tns:friends></tns:user></tns:userlist>
